version: 2
jobs:
  build:
    working_directory: /tmp/td-client-java
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test -Dtd.client.endpoint=api-staging.treasuredata.com
      - store_artifacts:
            path: /tmp/td-client-java/target/site
